/*! Cycle Start Studios - https://cyclestartstudios.com - offline worker */
// Generated by tools/make-pwa.mjs. Do not edit here: games/ is rebuilt on every sync.
const VERSION = '52aa90dc';
const CACHE = 'traffic-jam-' + VERSION;
const ASSETS = [
  "./fonts/audiowide.woff2",
  "./fonts/mrdafoe.woff2",
  "./fonts/righteous.woff2",
  "./icon-192.png",
  "./icon-512.png",
  "./img/logo.png",
  "./index.html"
];
// Third-party runtime files. Best-effort: see tools/make-pwa.mjs.
const EXTRAS = [];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS).then(() =>
        // One failure here must not fail the install.
        Promise.all(EXTRAS.map((u) =>
          fetch(u, { mode: 'cors' }).then((r) => r.ok && c.put(u, r)).catch(() => {})))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('traffic-jam-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// The page is always cached under this one key. A navigation asks for the
// directory ('.../neon-serpent/'), which is a different cache key from the
// precached './index.html' - storing the fresh copy under the request URL would
// leave the offline fallback reading a stale entry forever.
const PAGE = './index.html';

// Network-first for the page, so an online player always gets the live build.
// Falls back to cache when the network is slow or gone.
function pageFirst(event) {
  return new Promise((resolve) => {
    let settled = false;
    const done = (r) => { if (!settled && r) { settled = true; resolve(r); } };
    const timer = setTimeout(() => caches.match(PAGE).then(done), 3000);
    fetch(event.request)
      .then((res) => {
        clearTimeout(timer);
        // waitUntil, or the worker can be stopped before the write lands and the
        // next offline launch serves the previous build.
        // Clone synchronously: caches.open() is async, and by the time its
        // callback runs the browser has consumed the body to render the page,
        // leaving nothing to store.
        if (res && res.ok) {
          const copy = res.clone();
          event.waitUntil(caches.open(CACHE).then((c) => c.put(PAGE, copy)));
        }
        done(res);
      })
      .catch(() => {
        clearTimeout(timer);
        caches.match(PAGE).then((c) => {
          done(c);
          if (!c) resolve(new Response('offline', { status: 503, headers: { 'Content-Type': 'text/plain' } }));
        });
      });
  });
}

// Cache-first for assets, refreshed quietly in the background.
function assetFirst(event) {
  const req = event.request;
  return caches.match(req).then((hit) => {
    const net = fetch(req)
      .then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          event.waitUntil(caches.open(CACHE).then((c) => c.put(req, copy)));
        }
        return res;
      })
      .catch(() => hit);
    return hit || net;
  });
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) {
    // A third-party file the game needs: cache-first, so it works offline.
    if (EXTRAS.indexOf(req.url) !== -1) {
      e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
    }
    // Everything else off-site (the analytics beacon) is left alone: never
    // cached, and a failure offline must not take the game down with it.
    return;
  }
  e.respondWith(req.mode === 'navigate' ? pageFirst(e) : assetFirst(e));
});
