#!/usr/bin/env node
// Make a game installable and playable offline.
//
// Writes a web app manifest and a service worker into games/<slug>/, and wires
// both into its index.html. Run AFTER tools/minify.mjs, because the service
// worker precaches the files as they actually ship and is versioned by their
// contents.
//
// Why the pieces live where they do:
//   - Icons are authored once and kept in pwa/<slug>/. sync-games.sh wipes
//     games/<slug>/ on every sync, so anything generated there is disposable;
//     the icons are copied in at build time from the copy that survives.
//   - The service worker must sit at games/<slug>/sw.js: a worker's scope is
//     its own directory, so this one controls exactly its game and nothing else.
//
// Update strategy (this is the part that matters, given how often games ship):
//   - The page itself is network-first with a short timeout. Online, a player
//     always gets the build that is live right now; offline, they get the last
//     one they played. No "stuck on a week-old version".
//   - Everything else is cache-first and refreshed in the background.
//   - The cache name carries a hash of the build, so a new build lands in a new
//     cache and the old one is deleted on activate.
//
// Usage: node tools/make-pwa.mjs games/<slug> [...]

import { readFile, writeFile, readdir, stat, copyFile, access } from 'node:fs/promises';
import { join, relative, basename } from 'node:path';
import { createHash } from 'node:crypto';

const THEME_FALLBACK = '#120829';

// Third-party files a game needs at runtime. Cached best-effort so the game can
// still run with no network. Kept out of the main precache on purpose: addAll()
// rejects as a whole if any one request fails, and a CDN being unreachable must
// not stop the game installing.
const EXTRAS = {
  'pocket-dice': [
    'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js',
    'https://cdn.jsdelivr.net/npm/cannon-es@0.20.0/dist/cannon-es.js',
  ],
};

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}

const exists = (p) => access(p).then(() => true, () => false);

async function run(gameDir) {
  const slug = basename(gameDir);
  const iconSrc = join('pwa', slug);

  // Icons are required: without a 192 and a 512 the browser will not offer to install.
  for (const n of [192, 512]) {
    if (!(await exists(join(iconSrc, `icon-${n}.png`)))) {
      throw new Error(`${slug}: missing ${iconSrc}/icon-${n}.png - see MAINTENANCE.md`);
    }
    await copyFile(join(iconSrc, `icon-${n}.png`), join(gameDir, `icon-${n}.png`));
  }

  const games = JSON.parse(await readFile('games.json', 'utf8'));
  const game = games.find((g) => g.slug === slug);
  if (!game) throw new Error(`${slug}: no entry in games.json`);

  const htmlPath = join(gameDir, 'index.html');
  let html = await readFile(htmlPath, 'utf8');
  const theme = (html.match(/<meta name="theme-color" content="([^"]+)"/i) || [])[1] || THEME_FALLBACK;

  // What to precache: everything that ships except the site's own card image,
  // which only the landing page uses, and the worker itself.
  const files = (await walk(gameDir))
    .map((f) => relative(gameDir, f))
    .filter((f) => f !== 'thumb.png' && f !== 'sw.js' && f !== 'manifest.webmanifest')
    .sort();

  const h = createHash('sha256');
  for (const f of files) h.update(f).update(await readFile(join(gameDir, f)));
  const version = h.digest('hex').slice(0, 8);

  const manifest = {
    name: game.title,
    short_name: game.title,
    description: game.description,
    start_url: './',
    scope: './',
    display: 'standalone',
    background_color: theme,
    theme_color: theme,
    icons: [
      { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
  await writeFile(join(gameDir, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2) + '\n');

  const sw = `/*! Cycle Start Studios - https://cyclestartstudios.com - offline worker */
// Generated by tools/make-pwa.mjs. Do not edit here: games/ is rebuilt on every sync.
const VERSION = '${version}';
const CACHE = '${slug}-' + VERSION;
const ASSETS = ${JSON.stringify(files.map((f) => './' + f), null, 2)};
// Third-party runtime files. Best-effort: see tools/make-pwa.mjs.
const EXTRAS = ${JSON.stringify(EXTRAS[slug] || [], null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS).then(() =>
        // One failure here must not fail the install.
        Promise.all(EXTRAS.map((u) =>
          fetch(u, { mode: 'cors' }).then((r) => r.ok && c.put(u, r)).catch(() => {})))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('${slug}-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// The page is always cached under this one key. A navigation asks for the
// directory ('.../neon-serpent/'), which is a different cache key from the
// precached './index.html' - storing the fresh copy under the request URL would
// leave the offline fallback reading a stale entry forever.
const PAGE = './index.html';

// Network-first for the page, so an online player always gets the live build.
// Falls back to cache when the network is slow or gone.
function pageFirst(event) {
  return new Promise((resolve) => {
    let settled = false;
    const done = (r) => { if (!settled && r) { settled = true; resolve(r); } };
    const timer = setTimeout(() => caches.match(PAGE).then(done), 3000);
    fetch(event.request)
      .then((res) => {
        clearTimeout(timer);
        // waitUntil, or the worker can be stopped before the write lands and the
        // next offline launch serves the previous build.
        // Clone synchronously: caches.open() is async, and by the time its
        // callback runs the browser has consumed the body to render the page,
        // leaving nothing to store.
        if (res && res.ok) {
          const copy = res.clone();
          event.waitUntil(caches.open(CACHE).then((c) => c.put(PAGE, copy)));
        }
        done(res);
      })
      .catch(() => {
        clearTimeout(timer);
        caches.match(PAGE).then((c) => {
          done(c);
          if (!c) resolve(new Response('offline', { status: 503, headers: { 'Content-Type': 'text/plain' } }));
        });
      });
  });
}

// Cache-first for assets, refreshed quietly in the background.
function assetFirst(event) {
  const req = event.request;
  return caches.match(req).then((hit) => {
    const net = fetch(req)
      .then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          event.waitUntil(caches.open(CACHE).then((c) => c.put(req, copy)));
        }
        return res;
      })
      .catch(() => hit);
    return hit || net;
  });
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) {
    // A third-party file the game needs: cache-first, so it works offline.
    if (EXTRAS.indexOf(req.url) !== -1) {
      e.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
    }
    // Everything else off-site (the analytics beacon) is left alone: never
    // cached, and a failure offline must not take the game down with it.
    return;
  }
  e.respondWith(req.mode === 'navigate' ? pageFirst(e) : assetFirst(e));
});
`;
  await writeFile(join(gameDir, 'sw.js'), sw);

  // Wire it into the page. Injected after minification, so keep it compact.
  const head =
    `<link rel="manifest" href="manifest.webmanifest">` +
    `<link rel="apple-touch-icon" href="icon-192.png">` +
    `<meta name="apple-mobile-web-app-capable" content="yes">` +
    `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">` +
    `<meta name="apple-mobile-web-app-title" content="${game.title.replace(/"/g, '&quot;')}">`;
  if (!/rel="manifest"/.test(html)) {
    html = html.replace(/<head\b[^>]*>/i, (m) => m + head);
  }
  // Install affordance.
  //
  // It lives bottom-right, which in several games is occupied - Pocket Dungeons
  // puts its d-pad there, Anvil & Acre its army buttons. Making it translucent
  // does NOT fix that: a see-through button still swallows the tap. What fixes
  // it is not being there. The browser fires beforeinstallprompt at load, when
  // the player is still on a title screen, so the button shows then and retires
  // itself after 15s - long gone by the time anyone is playing.
  //
  // Dismissing it is remembered per game (the whole site shares one origin, so
  // the key carries the slug), and it gives up after three ignored showings.
  const install =
    `<style>#csx-install{position:fixed;right:12px;bottom:12px;z-index:2147483000;` +
    `display:flex;align-items:center;gap:9px;` +
    `font:600 12px/1 system-ui,sans-serif;letter-spacing:.04em;color:rgba(255,255,255,.92);` +
    `background:rgba(18,8,41,.6);border:1px solid rgba(255,255,255,.2);border-radius:999px;` +
    `padding:9px 10px 9px 15px;backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px);` +
    `box-shadow:0 2px 12px rgba(0,0,0,.35);opacity:0;transition:opacity .4s ease}` +
    `#csx-install.on{opacity:1}` +
    `#csx-install button{all:unset;cursor:pointer}` +
    `#csx-install .csx-go{padding:2px 2px 2px 0}` +
    `#csx-install .csx-x{padding:0 4px;opacity:.6;font-size:15px;line-height:1}` +
    `#csx-install .csx-x:hover{opacity:1}` +
    `@media(display-mode:standalone){#csx-install{display:none}}</style>` +
    `<script>(function(){` +
    `var K='csx.install.${slug}',p=null,el=null,t=null;` +
    `function seen(){try{return JSON.parse(localStorage.getItem(K))||{}}catch(e){return {}}}` +
    `function save(v){try{localStorage.setItem(K,JSON.stringify(v))}catch(e){}}` +
    `function retire(perm){if(t)clearTimeout(t);t=null;if(!el)return;` +
    `var e=el;el=null;e.classList.remove('on');setTimeout(function(){e.remove()},450);` +
    `var s=seen();if(perm)s.no=1;save(s)}` +
    `addEventListener('beforeinstallprompt',function(ev){ev.preventDefault();p=ev;` +
    `var s=seen();if(s.no||(s.n||0)>=3||el)return;s.n=(s.n||0)+1;save(s);` +
    `el=document.createElement('div');el.id='csx-install';` +
    `el.innerHTML='<button class="csx-go" type="button">Install</button>' +` +
    `'<button class="csx-x" type="button" aria-label="Dismiss">\\u00d7</button>';` +
    `el.querySelector('.csx-go').onclick=function(){var q=p;p=null;retire(1);if(q)q.prompt()};` +
    `el.querySelector('.csx-x').onclick=function(){retire(1)};` +
    `document.body.appendChild(el);` +
    `requestAnimationFrame(function(){if(el)el.classList.add('on')});` +
    `t=setTimeout(function(){retire(0)},15000)});` +
    `addEventListener('appinstalled',function(){p=null;retire(1)})})();</script>`;
  const reg =
    `<script>if('serviceWorker' in navigator)addEventListener('load',function(){` +
    `navigator.serviceWorker.register('sw.js').catch(function(){})});</script>`;
  if (!/serviceWorker/.test(html)) {
    html = html.replace(/<\/body>/i, () => install + reg + '</body>');
  }
  await writeFile(htmlPath, html);

  const bytes = (await Promise.all(files.map((f) => stat(join(gameDir, f)).then((s) => s.size))))
    .reduce((a, b) => a + b, 0);
  console.log(
    `  pwa ${slug}: v=${version}, ${files.length} files precached ` +
    `(${(bytes / 1024).toFixed(0)}K offline)`
  );
}

const targets = process.argv.slice(2);
if (!targets.length) {
  console.error('usage: node tools/make-pwa.mjs games/<slug> [...]');
  process.exit(2);
}
for (const t of targets) {
  if (!(await stat(t).catch(() => null))?.isDirectory()) {
    console.error(`not a directory: ${t}`);
    process.exit(2);
  }
  await run(t);
}
